### ISSUE TITLE
Error when analyzing a sequence

### ISSUE THREAD

**Issue by h170607** [adamhockenberry/bacphlip-py#13]
Analysis of a sequence always makes an error. But swapping the sequence (excluding the sequence name) to another works fine, I want to know what's special about this sequence.

The sequence is:
>k141_4828_flag=0_multi=1.0000_len=327
ATTATCAAAAAGGATCTTCACCTAGATCCTTTTAAATTAAAAATGAAGTTTTAAATCAATCTAAAGTATATATTATTAAACTTGGTCTGACAGATACCAAGTTAACTCATATTTACTTTAGATTGTTTTAAAAATTAAGATTTAAATCAACCTAAAGTATATATTAGTAAACTAGGTCTGACAGTTACCAGGTTTACTCATATATACTTTAGATTGATTTAAAACTTCATTTTTAATTTAAAAGGATCTAGGTGAAGTTCCTTTTTGATAATCTCATGACCAAAATCCCTTAAAGTGAGTTTTCGTTCAACTGAGCGTCAGACCCCG

The command is:
`bacphlip -i bacphlip_votu/k141_4828b.fa --local_hmmsearch home/share/Soft/hmmer-3.4/src/hmmsearch -f`

The error message is:

> Beginning BACPHLIP pipeline
> Finished six frame translation of genome (nucleotide) with output stored in bacphlip_votu/k141_4828b.fa.6frame
> 
> Error: Sequence file bacphlip_votu/k141_4828b.fa.6frame is empty or misformatted
> 
> Traceback (most recent call last):
>   File "/home/tj2024/.conda/envs/bacphlip/lib/python3.8/site-packages/bacphlip/bacphlip.py", line 217, in hmmsearch_py
>     subprocess.run(args=[hmmsearch_call, HMMER_DB, aa_fasta_file], check=True, stdout=outfile)
>   File "/home/tj2024/.conda/envs/bacphlip/lib/python3.8/subprocess.py", line 516, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['/groups/g900020/home/share/Soft/hmmer-3.4/src/hmmsearch', '/home/tj2024/.conda/envs/bacphlip/lib/python3.8/site-packages/bacphlip/data/prot_models.hmm', 'bacphlip_votu/k141_4828b.fa.6frame']' returned non-zero exit status 1.

**Comment by wanghang7410** [comment]
Have you solved it yet
