### ISSUE TITLE
Add support for multiple sequences in FASTA

### ISSUE THREAD

**Issue by snayfach** [adamhockenberry/bacphlip-py#4]
It would be really useful if you could provide support for multiple sequences per FASTA file:

```$ bacphlip -i test.fna
#################################################################################
Beginning BACPHLIP pipeline
Traceback (most recent call last):
  File "/global/homes/s/snayfach/.conda/envs/bacphlip/bin/bacphlip", line 8, in <module>
    sys.exit(main())
  File "/global/homes/s/snayfach/.conda/envs/bacphlip/lib/python3.8/site-packages/bacphlip/command_line.py", line 8, in main
    bacphlip.run_pipeline(args.input_file, force_overwrite=args.force_overwrite, local_hmmsearch=args.local_hmmsearch)
  File "/global/homes/s/snayfach/.conda/envs/bacphlip/lib/python3.8/site-packages/bacphlip/bacphlip.py", line 225, in run_pipeline
    six_frame_translate(input_file_path, six_frame_file, force_overwrite=force_overwrite)
  File "/global/homes/s/snayfach/.conda/envs/bacphlip/lib/python3.8/site-packages/bacphlip/bacphlip.py", line 85, in six_frame_translate
    nt_record = check_genome_fasta_reqs(nt_records)
  File "/global/homes/s/snayfach/.conda/envs/bacphlip/lib/python3.8/site-packages/bacphlip/bacphlip.py", line 65, in check_genome_fasta_reqs
    raise Exception("Input fasta file appears to contain more than one sequence record. "
Exception: Input fasta file appears to contain more than one sequence record. Currently bacphlip only supports single contig inputs.
```

**Comment by adamhockenberry** [comment]
Currently in progress, will try and update you when this feature is pushed. Thanks for the feedback

**Comment by adamhockenberry** [comment]
This should now be possible by providing the --multi_fasta run-time flag. Please see updated docs and note that all sequence records in the multifasta must have unique id's (as parsed by biopython, which is used to extract record id's) in order to write relevant files. Thanks for the feedback and let me know if you have any issues, still writing a few tests for this functionality but it seems stable in my hands.
